### ISSUE TITLE
Database and migrations commented

### ISSUE THREAD

**Issue by oscarthorn** [jetbridge/sst-prisma#41]
Hi!

Thanks for a great template!

Is it on purpose that the database and database migration constructs are commented out in the latest two commits (in stacks/index.ts)? How so? Wont that cause them to not be deployed?

**Comment by revmischa** [comment]
I'll uncomment them, thanks!
I need to do a new version for prisma 4.8.0, migrations changed a bit, also trying to get SST2 incorporated, so lots to update
