### ISSUE TITLE
`sst-prisma` it does not "just works" on initial setup.. fails on `pnpm start`

### ISSUE THREAD

**Issue by fddayan** [jetbridge/sst-prisma#42]
Hi I was doing the initial setup and run `pnpm install` and `pnpm start` and I'm getting 

`cp: /Users/federicodayan/projects/sst/sst-prisma/web/.next/standalone/web/.next/required-server-files.json: No such file or directory`

I was getting a `esbuild` version problem: `Cannot start service: Host version "0.15.16" does not match binary version "0.14.51"`, but I added `"esbuild": "0.14.51"` to root `package.json` and that fixed it.

This is the screenshot of the full error:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/188936/215338704-3ea2b427-661f-4179-9d55-f59f87d7b353.png">

**Comment by revmischa** [comment]
That's an issue with the nextjs construct dep. SST2 is coming out very soon with a new and improved NextjsSite construct. I will update this repo to use these when it's more stable.

Yes for now hardcoding esbuild should get you through it. Thanks.

**Comment by Johnrobmiller** [comment]
bump, getting the same error

**Comment by Johnrobmiller** [comment]
installing esbuild with `pnpm i --save-exact esbuild` did not work, and it's not clear from the error message where in the repo the issue is. This is a bit trickier to fix than I was hoping

**Comment by Johnrobmiller** [comment]
> Yes for now hardcoding esbuild should get you through it. Thanks.

A little more info would be helfpul 👍

**Comment by Johnrobmiller** [comment]
I spent about two hours debugging this. Unfortunately I'm just going to have to give up on this template. I don't think the solution is as simple as "hardcode esbuild".

**Comment by revmischa** [comment]
Ok, I will try to update to NextjsSite in SST2 this week, should make things better

**Comment by revmischa** [comment]
Can you please give the latest master version a try?
It is now `pnpm dev` to be consistent with SST2 and next

**Comment by revmischa** [comment]
Please let me know if any further issues. This should be resolved now
