### ISSUE TITLE
Error when running "pnpm start" for the first time; module not found

### ISSUE THREAD

**Issue by Johnrobmiller** [jetbridge/sst-prisma#44]
OS: mac (with the m1 processor)
node version: 16
date this template was downloaded: 2/12/23

This was after running `pnpm i`. Here is the error message in full:

<img width="989" alt="image" src="https://user-images.githubusercontent.com/55205360/218346469-52a6c07e-9892-4d8c-94c3-137aa66f44a2.png">

**Comment by revmischa** [comment]
Can you try the latest master?

**Comment by revmischa** [comment]
Please let me know if any further issues. This should be resolved now
