### ISSUE TITLE
Cannot find module ../package.json

### ISSUE THREAD

**Issue by willruggiano** [jetbridge/sst-prisma#48]
I am trying to do something similar, albeit not using your exact template. So, I understand if you don't have any pointers.

I have everything bundled, including a Lambda layer that provides the Prisma migration sdk. However, when executing the lambda I get an error:
```
Error: Cannot find module '../package.json'
```

which I believe is coming from within Migrate.ts, here: https://github.com/prisma/prisma/blob/main/packages/migrate/src/Migrate.ts#L12

When I look at the Lambda archive, it seems like everything is in the right place:
```
│     │  │  │  │  ├── Migrate.js
│     │  │  │  ├── package.json
│     │  │  │  └── README.md

```

Just wondering if you guys have seen this error before and might know how to fix it. If not, no worries!

**Comment by Rudey12** [comment]
did you find any ways to solve it I too have the same problem I don't know how to solve it if you do a help will be appreciated .
![Screenshot (33)](https://github.com/jetbridge/sst-prisma/assets/120767276/c27a95d0-f7a9-465b-9930-a14ce21392bd)

**Comment by willruggiano** [comment]
I did not. For me at least, I think it might be related to how I am bundling my Lambda code, which is using esbuild.

**Comment by revmischa** [comment]
Please try out the new version! It fixes many things. Let me know if you still have issues.
