### ISSUE TITLE
node_modules/.prisma not generated using pnpm

### ISSUE THREAD

**Issue by dylansproule** [jetbridge/sst-prisma#59]
Hello,

I've tried building/deploying the current repo as well as updating to the latest packages.  Neither seem to generate the node_modules/.prisma folder.

Any thoughts?

Thanks!

**Comment by revmischa** [comment]
Are you running `pnpm install`?
you can also run the `generate` package script manually. it should be run automatically after `pnpm install`

**Comment by dylansproule** [comment]
@revmischa I see, the folder structure I setup didn't work out, yours works as expected using the provided.

Any plans to move to Aurora RDS serverless v2?

Thanks.

**Comment by dylansproule** [comment]
Thanks for the input.

I've tried out v2 and there were permissions issues for the migration
scripts.  How much is a considerable minimum spend out of curiosity?
Thanks!

**Comment by revmischa** [comment]
All the lambda functions would probably need access to the DB secrets to connect
I think 0.5ACU for a month is probably like $70 or $80, not counting VPC NATGW costs
